# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d1_mcd <- function(eta, y, res) {
    .Call(`_covmodUK_d1_mcd`, eta, y, res)
}

#' Hessian mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param res Memory initialization
#' @export
NULL

d2_mcd <- function(eta, y, res) {
    .Call(`_covmodUK_d2_mcd`, eta, y, res)
}

jacobian_mcd <- function(eta, res, d, S_row, S_col, rc_idx_s, rc_idx_t, cor_flag) {
    .Call(`_covmodUK_jacobian_mcd`, eta, res, d, S_row, S_col, rc_idx_s, rc_idx_t, cor_flag)
}

#' Log-likelihood matrix mcd
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @export
NULL

ll_mcd <- function(eta, y) {
    .Call(`_covmodUK_ll_mcd`, eta, y)
}

lt_inversion <- function(X) {
    .Call(`_covmodUK_lt_inversion`, X)
}

mcd_LD <- function(x, d) {
    .Call(`_covmodUK_mcd_LD`, x, d)
}

mcd_Sigma <- function(L, D, d) {
    .Call(`_covmodUK_mcd_Sigma`, L, D, d)
}

mcd_decomposition <- function(X) {
    .Call(`_covmodUK_mcd_decomposition`, X)
}

precision <- function(X) {
    .Call(`_covmodUK_precision`, X)
}

pred_mcd <- function(eta, res, d, cor_flag) {
    .Call(`_covmodUK_pred_mcd`, eta, res, d, cor_flag)
}

#' Residuals vector via mcd parameterisation
#'
#' @param eta Linear predictor (n x (d + dx(d+1)/2) matrix).
#' @param y Outcome (n x d matrix).
#' @param y res (n x d matrix).
#' @export
NULL

res_dev_mcd <- function(eta, y, res) {
    .Call(`_covmodUK_res_dev_mcd`, eta, y, res)
}

